---
title: "cli color palettes"
author: "Gábor Csárdi"
date: "`r Sys.Date()`"
output:
  html_document:
    css: "palettes.css"
editor_options:
  markdown:
    wrap: sentence
---

```{r, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%",
  cache = TRUE
)
# Turn on ANSI colors
options(cli.num_colors = cli::truecolor)
asciicast::init_knitr_engine(
  startup = quote({
    library(cli)
    set.seed(1) }),
  echo = TRUE,
  echo_input = FALSE,
  options = list(
    asciicast_theme = list(background = c(255, 255, 255, 0), text = c(51, 51, 51)),
    asciicast_cols = 80
  ))
```

# Built-in palettes

## dichro

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$dichro)
```

```{asciicast, dichro, echo = FALSE}
ansi_palette_show("dichro", colors = truecolor)
```

```{asciicast, dichro-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("dichro", colors = truecolor)
```

## vga

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$vga)
```

```{asciicast, vga, echo = FALSE}
ansi_palette_show("vga", colors = truecolor)
```

```{asciicast, vga-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("vga", colors = truecolor)
```

## winxp

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$winxp)
```

```{asciicast, winxp, echo = FALSE}
ansi_palette_show("winxp", colors = truecolor)
```

```{asciicast, winxp-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("winxp", colors = truecolor)
```

## vscode

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$vscode)
```

```{asciicast, vscode, echo = FALSE}
ansi_palette_show("vscode", colors = truecolor)
```

```{asciicast, vscode-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("vscode", colors = truecolor)
```

## win10

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$win10)
```

```{asciicast, win10, echo = FALSE}
ansi_palette_show("win10", colors = truecolor)
```

```{asciicast, win10-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("win10", colors = truecolor)
```

## macos

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$macos)
```

```{asciicast, macos, echo = FALSE}
ansi_palette_show("macos", colors = truecolor)
```

```{asciicast, macos-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("macos", colors = truecolor)
```

## putty

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$putty)
```

```{asciicast, putty, echo = FALSE}
ansi_palette_show("putty", colors = truecolor)
```

```{asciicast, putty-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("putty", colors = truecolor)
```

## mirc

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$mirc)
```

```{asciicast, mirc, echo = FALSE}
ansi_palette_show("mirc", colors = truecolor)
```

```{asciicast, mirc-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("mirc", colors = truecolor)
```

## xterm

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$xterm)
```

```{asciicast, xterm, echo = FALSE}
ansi_palette_show("xterm", colors = truecolor)
```

```{asciicast, xterm-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("xterm", colors = truecolor)
```

## ubuntu

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$ubuntu)
```

```{asciicast, ubuntu, echo = FALSE}
ansi_palette_show("ubuntu", colors = truecolor)
```

```{asciicast, ubuntu-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("ubuntu", colors = truecolor)
```

## eclipse

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$eclipse)
```

```{asciicast, eclipse, echo = FALSE}
ansi_palette_show("eclipse", colors = truecolor)
```

```{asciicast, eclipse-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("eclipse", colors = truecolor)
```

## iterm

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$iterm)
```

```{asciicast, iterm, echo = FALSE}
ansi_palette_show("iterm", colors = truecolor)
```

```{asciicast, iterm-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("iterm", colors = truecolor)
```

## iterm-pastel

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$`iterm-pastel`)
```

```{asciicast, iterm-pastel, echo = FALSE}
ansi_palette_show("iterm-pastel", colors = truecolor)
```

```{asciicast, iterm--pastel-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("iterm-pastel", colors = truecolor)
```

## iterm-smoooooth

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$`iterm-smoooooth`)
```

```{asciicast, iterm-smoooooth, echo = FALSE}
ansi_palette_show("iterm-smoooooth", colors = truecolor)
```

```{asciicast, iterm--smoooooth-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("iterm-smoooooth", colors = truecolor)
```

## iterm-snazzy

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$`iterm-snazzy`)
```

```{asciicast, iterm-snazzy, echo = FALSE}
ansi_palette_show("iterm-snazzy", colors = truecolor)
```

```{asciicast, iterm--snazzy-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("iterm-snazzy", colors = truecolor)
```

## iterm-solarized

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$`iterm-solarized`)
```

```{asciicast, iterm-solarized, echo = FALSE}
ansi_palette_show("iterm-solarized", colors = truecolor)
```

```{asciicast, iterm--solarized-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("iterm-solarized", colors = truecolor)
```

## iterm-tango

```{r, results = "asis", echo = FALSE}
cat(attr(cli::ansi_palettes, "info")$`iterm-tango`)
```

```{asciicast, iterm-tango, echo = FALSE}
ansi_palette_show("iterm-tango", colors = truecolor)
```

```{asciicast, iterm--tango-dark, echo = FALSE, R.options = list(asciicast_theme = list(background = c(40, 45, 53), text = c(185, 192, 203)))}
ansi_palette_show("iterm-tango", colors = truecolor)
```
