
## The life of a cli status

You _create_ a cli status with [cli_status()] or [cli_process_start()]. cli
will show the new status in the status bar.

If neccessary, you _update_ a status with [cli_status_update()] or
[cli_process_update()].

You _terminate_ a status with [cli_status_clear()], [cli_process_done()] or
[cli_process_failed()]. When a status is terminated, it is removed from the
status bar. Before that, it may still print a final summary message, which
you can specify using the `msg_done` and `msg_failed` arguments.

cli can also auto-terminate a status, see 'Automatic termination' below.

A status has three modes of termination:
* `clear`: The status is removed from the status bar.
* `done`: The status is removed from the status bar, but its `msg_done`
  message is printed as a regular cli message. This is typically a short
  summary of a task that has just finished, e.g.
  `Downloaded 14 files (1.5MB).`"
* `failed`: The status is removed from the status bar, and its `msg_failed`
  message is printed as a regular cli message. (For auto-termination caused
  by an R error, this message typically shows up _under_ R's error message.)

## Status ids and the current status

When you create a status cli assigns an id to it. This id can be used to
update or terminate the status.

If you don't specify the id in [cli_status_update()],
[cli_process_update()], etc. then cli will manipulate the _current status_.
The current status is the one that was last created in the caller
(or in `.envir` if specified). This allows simpler code:

```r
done <- 0
cli_process_start("Downloading data files: {done}/{total}")
for (done in seq_len(total)) {
  ...
  cli_process_update()
}

...

done <- 0
cli_process_start("Processing data files: {done}/{total}")
for (done in seq_len(total)) {
  ...
  cli_process_update()
}
```

Here the [cli_process_update()] calls refer to previoues [cli_status()]
calls.

Also note that we didn't have to terminate the first status explicitly,
thanks to cli's automatic termination, see the next section.

A similar example with the `cli_status*` API:

```r
done <- 0
cli_status("Downloading data files: {done}/{total}")
for (done in seq_len(total)) {
  ...
  cli_status_update()
}

...

done <- 0
cli_status("Processing data files: {done}/{total}")
for (done in seq_len(total)) {
  ...
  cli_status_update()
}
```

## Automatic termination

Usually you will want the status to terminate automatically if an
error happens and/or the function that created it quits.

In most cases you also want to terminate the status if another
status is created from the same called, via [cli_status()] or
[cli_process_start()].

If the `.auto_close` argument of [cli_status()] and [cli_process_start()]
is `TRUE` (the default), then cli will automatically terminate the status
is these cases. This helps to reduce the clutter in the code caused by cli
messages.

If you don't want to terminate a status automatically, you need to specify
`.auto_close = FALSE`. In this case, we suggest that you add an [on.exit()]
or [withr::defer()] handler that terminates the status, to avoid keeping
it on the screen after an error or interruption happens.

## Multiple active statuses

It is possible to have multiple active cli statuses at the same time.
This may happen when you creates statues from nested function calls, or
when you specify `.auto_close = FALSE`.

Nested statuses "just work" in general: if a nested level status terminates,
cli will automatically show its immediate nesting status in the status bar.

Currently, when you update a status, cli will show it in the status bar,
even if it there are other statuses nested "inside" it. This behavior might
change in the future, as it can cause flickering when multiple statuses are
updated frequently.
